version: "3"
services:
  site:
    environment:
      - JEKYLL_ENV=production
    command: jekyll serve
    image: jekyll/jekyll:latest
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
  build:
    environment:
      - JEKYLL_ENV=production
    command: jekyll build
    image: jekyll/jekyll:latest
    volumes:
      - .:/srv/jekyll
